openapi: 3.0.3
info:
  title: "Quiz Master Admin API"
  version: "1.0.0"
  description: >
    API endpoints for admin-only data access.  
    Requires: user must be logged in with 'role=admin' in the Flask session.

servers:
  - url: "http://127.0.0.1:5000"
    description: "Local Development Server"

paths:
  /admin/api/users:
    get:
      summary: "Get All Users"
      description: >
        Returns a JSON array of all registered users.
      responses:
        '200':
          description: A list of user objects in JSON
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    full_name:
                      type: string
                    qualification:
                      type: string
                    dob:
                      type: string
                    role:
                      type: string
        '401':
          description: "Unauthorized if `role=admin` is not present in session"

  /admin/api/subjects:
    get:
      summary: "Get All Subjects"
      description: >
        Returns a JSON array of all subjects.
      responses:
        '200':
          description: JSON array of subject objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
        '401':
          description: "Unauthorized if not logged in as admin"

  /admin/api/subjects/{subject_id}/chapters:
    get:
      summary: "Get Chapters by Subject"
      description: >
        Returns chapters (JSON array) under a given subject.
      parameters:
        - name: subject_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the subject
      responses:
        '200':
          description: JSON array of chapter objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
        '401':
          description: "Unauthorized if not logged in as admin"
        '404':
          description: "Subject not found"

  /admin/api/chapters/{chapter_id}/quizzes:
    get:
      summary: "Get Quizzes by Chapter"
      description: >
        Returns quizzes (JSON array) for a given chapter.
      parameters:
        - name: chapter_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the chapter
      responses:
        '200':
          description: JSON array of quiz objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    date_of_quiz:
                      type: string
                    time_duration:
                      type: string
                    remarks:
                      type: string
        '401':
          description: "Unauthorized if not logged in as admin"
        '404':
          description: "Chapter not found"

  /admin/api/scores:
    get:
      summary: "Get All Scores"
      description: >
        Returns JSON array of all quiz scores.  
      responses:
        '200':
          description: JSON array of score objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    quiz_id:
                      type: integer
                    user_id:
                      type: integer
                    time_stamp_of_attempt:
                      type: string
                    total_scored:
                      type: integer
        '401':
          description: "Unauthorized if not logged in as admin"
